version: '3.9'

services:
  cassandra_db:
    container_name: cassandra_db
    build:
      dockerfile: Dockerfile
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=tutorial-cluster
    networks:
      - cassandra_network

  cassandra_temp:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./scripts/bash:/docker-entrypoint.sh
      - ./scripts/cql:/tmp/cql
    networks:
      - cassandra_network
    command: >
      bash -c "dos2unix ./docker-entrypoint.sh/execute-cql.sh &&
               chmod +x ./docker-entrypoint.sh/execute-cql.sh &&
               ./docker-entrypoint.sh/execute-cql.sh"
networks:
  cassandra_network:
